version: '3.7'

services:
  redis:
    image: redis
    ports:
      - 6379:6379
    command: redis-server --requirepass mypass

  postgres:
    image: postgres:10-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: workflow-service

  es:
    image: elasticsearch:7.4.1
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      discovery.type: single-node
      cluster.routing.allocation.disk.threshold_enabled: "false"
