---
apiVersion: v1
kind: Secret
metadata:
  name: {{.WORKFLOW_SERVICE_NAME}}
type: Opaque
data:
  awsAccessKeyId: "{{.AWS_ACCESS_KEY | b64enc }}"
  awsSecretAccessKey: "{{.AWS_SECRET_KEY | b64enc }}"
