---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: {{.WORKFLOW_SERVICE_NAME}}
  name: {{.WORKFLOW_SERVICE_NAME}}
spec:
  ports:
  - name: https
    port: 443
    targetPort: 8443
  selector:
    name: {{.WORKFLOW_SERVICE_NAME}}
