# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Service Builder API Test and Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: joschi/setup-jdk@v1
        with:
          java-version: 'openjdk14' // The OpenJDK version to make available on the path
          architecture: 'x64' // defaults to 'x64'
          openjdk_impl: 'openj9'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Run tests
        run: ./gradlew clean test
